// Copyright (C) 2026 Chris Kearney
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, version 3.
//
// SPDX-License-Identifier: GPL-3.0-only
//
// Auteur is an agentic music-video studio: it turns a music track, optional
// reference imagery, and a producer's prompt into a finished music video,
// generated by a director agent and its specialist crew.
package main

import (
	"bufio"
	"context"
	"flag"
	"fmt"
	"log/slog"
	"net/http"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"

	"auteur/internal/agents"
	"auteur/internal/server"
	"auteur/internal/studio"
	"auteur/pkg/comfy"
	"auteur/pkg/elevenlabs"
	"auteur/pkg/harness"
	"auteur/pkg/minimax"
	"auteur/pkg/xai"
)

func main() {
	addr := flag.String("addr", "127.0.0.1:7788", "listen address")
	dataDir := flag.String("data", "workspaces", "productions root directory")
	skillsDir := flag.String("skills", "skills", "skills directory")
	model := flag.String("model", envOr("AUTEUR_MODEL", xai.DefaultChatModel), "chat model for agents")
	viewer := flag.Bool("viewer", false, "observe-only instance: no run control, no stale-state recovery")
	videoEngine := flag.String("video", envOr("AUTEUR_VIDEO", agents.EngineGrok),
		"clip renderer: 'grok' (hosted Grok Imagine), 'h3' (MiniMax H3 on the local ComfyUI), "+
			"or 'minimax' (MiniMax H3 on the hosted minimax.io API)")
	h3URL := flag.String("h3-url", envOr("AUTEUR_H3_URL", "http://127.0.0.1:8189"),
		"ComfyUI base URL(s) for the h3 renderer; comma-separate to pool render nodes")
	h3Steps := flag.Int("h3-steps", 8, "H3 sampling steps (8 matches the turbo LoRA)")
	flag.Parse()

	loadDotEnv(".env")

	apiKey := os.Getenv("XAI_API_KEY")
	if apiKey == "" {
		fatal("XAI_API_KEY is not set (put it in .env or the environment)")
	}
	for _, bin := range []string{"ffmpeg", "ffprobe"} {
		if _, err := exec.LookPath(bin); err != nil {
			fatal(bin + " not found in PATH; install ffmpeg")
		}
	}

	video, err := buildVideoEngine(*videoEngine, *h3URL, *h3Steps)
	if err != nil {
		fatal(err.Error())
	}

	newStudio := studio.New
	if *viewer {
		newStudio = studio.NewViewer
	}
	st, err := newStudio(*dataDir)
	if err != nil {
		fatal("init studio: " + err.Error())
	}
	skills, err := harness.LoadSkills(*skillsDir)
	if err != nil {
		fatal("load skills: " + err.Error())
	}

	// Film productions voice their lines with ElevenLabs; without a key the
	// studio still runs music videos, and film runs are refused at start.
	var eleven *elevenlabs.Client
	if key := os.Getenv("ELEVENLABS_API_KEY"); key != "" {
		eleven = elevenlabs.NewClient(key)
		if m := os.Getenv("ELEVENLABS_MODEL"); m != "" {
			eleven.Model = m
		}
		slog.Info("voice engine ready", "provider", "elevenlabs", "model", eleven.Model)
	} else {
		slog.Warn("ELEVENLABS_API_KEY not set: film mode (narrated productions) is disabled")
	}

	srv := &server.Server{
		Studio: st,
		XAI:    xai.NewClient(apiKey),
		Skills: skills,
		Model:  *model,
		Viewer: *viewer,
		Video:  video,
		Eleven: eleven,
	}

	slog.Info("auteur studio open", "addr", "http://"+*addr, "model", *model,
		"video", video.Kind, "data", absOrSelf(*dataDir))
	fmt.Printf("\n  AUTEUR - agentic music video studio\n  http://%s\n\n", *addr)
	if err := http.ListenAndServe(*addr, srv.Handler()); err != nil {
		fatal(err.Error())
	}
}

// buildVideoEngine resolves the -video flag, verifying up front that a local
// renderer is actually reachable rather than failing mid-production.
func buildVideoEngine(kind, h3URL string, steps int) (agents.VideoEngine, error) {
	switch kind {
	case agents.EngineGrok, "":
		return agents.VideoEngine{Kind: agents.EngineGrok}, nil
	case agents.EngineH3:
		var urls []string
		for _, u := range strings.Split(h3URL, ",") {
			if u = strings.TrimSpace(u); u != "" {
				urls = append(urls, u)
			}
		}
		pool := comfy.NewPool(urls)
		ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
		defer cancel()
		nodes, err := pool.Ping(ctx)
		for _, n := range nodes {
			slog.Info("h3 render node", "node", n)
		}
		if err != nil {
			return agents.VideoEngine{}, fmt.Errorf("h3 renderer: %w (urls: %s)\n"+
				"  start a ComfyUI instance serving MiniMax H3, then pass -h3-url", err, h3URL)
		}
		slog.Info("h3 render pool ready", "nodes", pool.Size(), "steps", steps)
		return agents.VideoEngine{Kind: agents.EngineH3, Pool: pool, Steps: steps}, nil
	case agents.EngineMiniMax:
		key := os.Getenv("MINIMAX_API_KEY")
		if key == "" {
			return agents.VideoEngine{}, fmt.Errorf("minimax renderer: MINIMAX_API_KEY is not set (put it in .env)")
		}
		client := minimax.NewClient(key)
		if base := os.Getenv("MINIMAX_BASE_URL"); base != "" {
			client.BaseURL = strings.TrimRight(base, "/")
		}
		slog.Info("minimax hosted renderer ready", "model", "MiniMax-H3", "base", client.BaseURL)
		return agents.VideoEngine{Kind: agents.EngineMiniMax, MiniMax: client}, nil
	default:
		return agents.VideoEngine{}, fmt.Errorf("unknown -video %q (want 'grok', 'h3', or 'minimax')", kind)
	}
}

func envOr(key, def string) string {
	if v := os.Getenv(key); v != "" {
		return v
	}
	return def
}

// loadDotEnv loads KEY=VALUE lines into the environment (no override).
func loadDotEnv(path string) {
	f, err := os.Open(path)
	if err != nil {
		return
	}
	defer f.Close()
	sc := bufio.NewScanner(f)
	for sc.Scan() {
		line := strings.TrimSpace(sc.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		key, val, ok := strings.Cut(line, "=")
		if !ok {
			continue
		}
		key, val = strings.TrimSpace(key), strings.Trim(strings.TrimSpace(val), `"'`)
		if os.Getenv(key) == "" {
			os.Setenv(key, val)
		}
	}
}

func absOrSelf(p string) string {
	if abs, err := filepath.Abs(p); err == nil {
		return abs
	}
	return p
}

func fatal(msg string) {
	fmt.Fprintln(os.Stderr, "auteur: "+msg)
	os.Exit(1)
}
